# -*- coding: utf-8 -*-
"""rugby_training_yolov5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZcv0yJg45fCWJHaPilJ8VMaIhBdpt7E
"""

!pip install ultralytics
!pip install roboflow

"""# Get Dataset"""

# rugby league dataset

from roboflow import Roboflow
rf = Roboflow(api_key="y80duBYM8z5s5hJy35Bi")
project = rf.workspace("aap-blocky-yqzrb").project("nrl-player-detection")
version = project.version(2)
dataset = version.download("yolov8")

"""# Training"""

!yolo task=detect mode=train model='yolov8s.pt' data={dataset.location}/data.yaml epochs=100 imgsz=640 patience=10